# Syntax version
version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: carsInventory_container
    image: mongo:latest
    ports:
      # host: mongodb container | external access 
      - 27018:27017
    restart: always
    volumes:
      # persistent data storage
      - mongo_data:/data/db

  # Node api service
  api:
    image: nodeapp
    ports:
      - 3050:3050
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}